on:
  workflow_call:

jobs:
  test:
    uses: EcommerceAppDeployment/roboshop-github-actions/.github/workflows/test.yml@main
    with:
      app_type: ${{ inputs.app_type }}

  build:
    needs: test
    uses: EcommerceAppDeployment/roboshop-github-actions/.github/workflows/build.yml@main
    with:
      app_type: ${{ inputs.app_type }}