on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted # Specifies the runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out the repository code

      - name : Run a line script
        run: echo Hello world
        
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out the repository code

      - name: Run tests
        run: echo 'running tests' # Example: Run tests

  qa-deploy:
    needs: test
    runs-on: self-hosted
    environment: qa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out the repository code

      - name: Run tests
        run: echo 'qa deployment'

  uat-deploy:
    needs: qa-deploy
    runs-on: self-hosted
    environment: uat
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out the repository code

      - name: Run tests
        run: echo 'uat deployment'
  
  prod-deploy:
    needs: uat-deploy
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out the repository code

      - name: Run tests
        run: echo 'prod'